/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/c_plusplus.glb --transform --typescript
Files: public/models/c_plusplus.glb [139.63KB] > C:\Users\PC\WebstormProjects\Tech\Portfolio_Website\c_plusplus-transformed.glb [41.47KB] (70%)
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c-1b277fc32bbc451fa6f40e298996ba91
Title: C++
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
    // Added /models/ to point correctly to your public folder
    const { nodes, materials } = useGLTF('/models/c_plusplus-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={(nodes as any)['C++_C++_0'].geometry}
                material={materials.material}
                position={[0, 0, 1.996]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

// Fixed preload path as well
useGLTF.preload('/models/c_plusplus-transformed.glb')