/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/c_sharp.glb --transform --typescript
Files: public/models/c_sharp.glb [144.38KB] > C:\Users\PC\WebstormProjects\Tech\Portfolio_Website\c_sharp-transformed.glb [40.84KB] (72%)
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c-e3a5d3e564a64fb0ab39665f44632520
Title: C#
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
    // Added /models/ to route to your public folder layout asset
    const { nodes, materials } = useGLTF('/models/c_sharp-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={(nodes as any)['C#_C#_0'].geometry}
                material={materials.material}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

// Fixed preload routing configuration
useGLTF.preload('/models/c_sharp-transformed.glb')
