/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/javascript_logo__3d_model.glb --transform --typescript
Files: public/models/javascript_logo__3d_model.glb [301.07KB] > C:\Users\PC\WebstormProjects\Tech\Portfolio_Website\javascript_logo__3d_model-transformed.glb [25.75KB] (91%)
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-logo-3d-model-792093fab435419ab70dae39d2891cb3
Title: JavaScript Logo – 3D Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
    // Added /models/ path prefix for public asset loading
    const { nodes, materials } = useGLTF('/models/javascript_logo__3d_model-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={(nodes as any).Object_4.geometry} material={materials.yellow} />
            <mesh geometry={(nodes as any).Object_5.geometry} material={materials.black} />
        </group>
    )
}

// Updated asset preloader destination
useGLTF.preload('/models/javascript_logo__3d_model-transformed.glb')