/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/react_logo.glb --transform --typescript
Files: public/models/react_logo.glb [1.43MB] > C:\Users\PC\WebstormProjects\Tech\Portfolio_Website\react_logo-transformed.glb [58.92KB] (96%)
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
    // Added /models/ path prefix for proper static asset routing
    const { nodes, materials } = useGLTF('/models/react_logo-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={(nodes as any)['React-Logo_Material002_0'].geometry}
                material={materials['Material.002']}
                position={[0, 0.079, 0.181]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.392, 0.392, 0.527]}
            />
        </group>
    )
}

// Updated the asset preloader location
useGLTF.preload('/models/react_logo-transformed.glb')