/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/typescript_logo__3d_model.glb --transform --typescript
Files: public/models/typescript_logo__3d_model.glb [305.85KB] > C:\Users\PC\WebstormProjects\Tech\Portfolio_Website\typescript_logo__3d_model-transformed.glb [24.5KB] (92%)
Author: Alex human (https://sketchfab.com/alex-human)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/typescript-logo-3d-model-84af2099cb8542549fb56eae0dbabdb5
Title: TypeScript Logo – 3D Model
*/

import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
    // Added /models/ path prefix for proper static asset routing
    const { nodes, materials } = useGLTF('/models/typescript_logo__3d_model-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={(nodes as any).Object_4.geometry} material={materials.blue} />
            <mesh geometry={(nodes as any).Object_5.geometry} material={materials.white} />
        </group>
    )
}

// Updated the asset preloader destination
useGLTF.preload('/models/typescript_logo__3d_model-transformed.glb')